<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="1331-MAPANMAC.local" failures="1" tests="1" name="Command line test" time="3.594" errors="0" timestamp="2021-07-28T10:52:55 WIB">
  <testcase classname="backend.api.TestHello" name="testUser" time="3.559">
    <failure type="java.lang.AssertionError" message="$.data.id has wrong value expected [5] but found [3]">
      <![CDATA[java.lang.AssertionError: $.data.id has wrong value expected [5] but found [3]
at util.validator.ResponseValidator.valueEqual(ResponseValidator.java:23)
at util.validator.ResponseValidator.valueEqual(ResponseValidator.java:27)
at backend.api.TestHello.testUser(TestHello.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- testUser -->
</testsuite> <!-- Command line test -->
